version: '3'
services:
  ovpn-client:
    image: romantix74/openvpn_client
#    container_name: ovpn_client
#    privileged: yes
    environment:
      - OPENVPN_SERVER=ru.secretvpn.net
      - OPENVPN_PORT=443
    volumes:
      - /etc/openvpn/:/etc/openvpn/
