version: '3'
services:
  ovpn-client:
    image: romantix74/openvpn_client
#    container_name: ovpn_client
    environment:
      - OPENVPN_SERVER=ru.secretvpn.net
      - OPENVPN_PORT=443
      - OPENVPN_PROTO=UDP
    privileged: true
    volumes:
      - /etc/openvpn/:/etc/openvpn/
